remote_theme: 'jekyll/minima'

## Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      title: 'COINE@AAMAS2024'

## General
title: 'International Workshop on Coordination, Organizations, Institutions, Norms and Ethics for Governance of Multi-Agent Systems (COINE@AAMAS2024)'
email: coineaamas2024@easychair.org
description: >-
url: 'https://coin-workshop.github.io/coine-2024-auckland'
baseurl: ''

markdown: kramdown

sass:
  sass_dir: assets/css
  style: expanded

exclude:
- README.md
